Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Data;
using SchoolProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using SchoolProject.Helper;

namespace SchoolProject.Controllers
{
    public class AdminController : Controller
    {
         private readonly ApplicationDBContext _context;

       public AdminController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
          
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account"); 
            }

            var personId = HttpContext.Session.GetInt32("PersonID");
            if (personId == null)
            {
                return RedirectToAction("Login", "Account"); 
            }

            var user = _context.Persons.FirstOrDefault(p => p.PersonID == personId);
            if (user == null)
            {
                return NotFound(); 
            }


            var model = new DashboardViewModel
            {
                NumberOfStudents = _context.Students.Count(),
                NumberOfTeachers = _context.Teachers.Count(),
                NumberOfStaffs = _context.Staffs.Count(),
                DateTime = DateTime.Now,
                FirstName = user.FirstName,
                LastName = user.LastName
            };

            return View(model);
        }


    }
}

Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolProject.Helper;
using SchoolProject.Data;
 

namespace SchoolProject.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDBContext _context;

        public CourseController(ApplicationDBContext context)
        {
            _context = context; 
        }
        public IActionResult Index()
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }

            var courses = _context.Courses .Include(c => c.CourseTeacher) 
                   .ThenInclude(t => t.TeacherPerson) 
                    .Include(c => c.CourseClass);

            return View(courses.ToList());

        }
        public IActionResult Create()
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }
            var teacherList = _context.Teachers
                .Include(t => t.TeacherPerson)
                .Select(t => new
                {
                    TeacherId = t.TeacherId,
                    FullName = t.TeacherPerson.FirstName + " " + t.TeacherPerson.LastName
                }).ToList();

            if (!teacherList.Any())
            {
                TempData["ErrorMessage"] = "No teachers available";
                return RedirectToAction("Index", "Teachers");
            }

            ViewBag.TeacherId = new SelectList(teacherList, "TeacherId", "FullName");
          ViewBag.ClassId= new SelectList(_context.Classes, "ClassId", "ClassName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

           
            var teacherList = _context.Teachers
                .Include(t => t.TeacherPerson)
                .Select(t => new
                {
                    TeacherId = t.TeacherId,
                    FullName = t.TeacherPerson.FirstName + " " + t.TeacherPerson.LastName
                }).ToList();

            if (!teacherList.Any())
            {
                TempData["ErrorMessage"] = "No teachers available";
                return RedirectToAction("Index", "Teachers");
            }

            ViewBag.TeacherId = new SelectList(teacherList, "TeacherId", "FullName", course.TeacherId);
            ViewBag.ClassId = new SelectList(_context.Classes, "ClassId", "ClassName", course.ClassId);

            return View(course);
        }
        public IActionResult Edit(int? id)
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }
            if (id == null)
            {
                return NotFound();
            }

            var cours = _context.Classes.Find(id);

            if (cours == null)
            {
                return NotFound();
            }

            var teacherList = _context.Teachers
                .Include(t => t.TeacherPerson)
                .Select(t => new
                {
                    TeacherId = t.TeacherId,
                    FullName = t.TeacherPerson.FirstName + " " + t.TeacherPerson.LastName 
                }).ToList();

            var classList = _context.Classes.ToList();

            ViewBag.TeacherId = new SelectList(teacherList, "TeacherId", "FullName");
            ViewBag.ClassId = new SelectList(classList, "ClassId", "ClassName");
            return View(cours);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Course course)
        {
            if (id != course.ClassId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }


            var teacherList = _context.Teachers
                .Include(t => t.TeacherPerson)
                .Select(t => new
                {
                    TeacherId = t.TeacherId,
                    FullName = t.TeacherPerson.FirstName + " " + t.TeacherPerson.LastName
                }).ToList();
           
            ViewBag.TeacherId = new SelectList(teacherList, "TeacherId", "FullName");
            ViewBag.ClassId = new SelectList(_context.Classes, "ClassId", "ClassName");
            return View(course);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                var Course = _context.Courses.
                    FirstOrDefault(c => c.CourseId == id);

                if (Course == null)
                {
                    return NotFound();
                }


                _context.Courses.Remove(Course);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                return BadRequest($"  Deletion failed: {ex.Message}");
            }
        }
        private bool CourseExists(int id)
        {
            return _context.Courses.Any(c => c.CourseId == id);
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolProject.Data;
using SchoolProject.Helper;

namespace SchoolProject.Controllers
{
    public class UsersController : Controller
    {

        public readonly ApplicationDBContext context;

        public UsersController(ApplicationDBContext context)
        {
            this.context = context;

        }
        public IActionResult Index(string searchQuery)
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }

            var users = context.Users
                .Include(u => u.UserPerson)
                .AsQueryable();


            if (!string.IsNullOrEmpty(searchQuery))
            {
                users = users.Where(u => u.Username.Contains(searchQuery) ||

                                         (u.UserPerson.FirstName.Contains(searchQuery) ||
                                          u.UserPerson.LastName.Contains(searchQuery)));  // البحث عن الاسم أو اسم المستخدم
            }

           
            var userList = users.Select(u => new UserDto
            {
                UserId = u.UserId,
                PersonID = u.UserPerson.PersonID,
                Username = u.Username,
                Password = u.Password,  
                FirstName = u.UserPerson.FirstName,
                LastName = u.UserPerson.LastName,
                Email = u.UserPerson.Email,
                contactNumber = u.UserPerson.contactNumber,
                Address = u.UserPerson.Address,
                DateOfBirth = u.UserPerson.DateOfBirth,
                Role = u.UserPerson.Role,
            }).ToList();

            return View(userList);
        }

        public IActionResult Create()
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }

			var personId = TempData["PersonID"] != null ? (int)TempData["PersonID"] : 0;
			ViewBag.PersonID = personId;

			return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                var newuser = new User
                {
                    PersonId = user.PersonId,
                    Username = user.Username,
                    Password = user.Password,
                };

                context.Users.Add(newuser);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        public IActionResult Edit(int id)
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }

            var user = context.Users
                .Include(u => u.UserPerson)
                .FirstOrDefault(u => u.UserId == id);

            if (user == null)
            {
                return NotFound();
            }

            var userDto = new UserDto
            {
                UserId = user.UserId,
                PersonID = user.UserPerson.PersonID,
                Username = user.Username,
                Password = user.Password,
                FirstName = user.UserPerson.FirstName,
                SecondName = user.UserPerson.SecondName,
                LastName = user.UserPerson.LastName,
                Email = user.UserPerson.Email,
                contactNumber = user.UserPerson.contactNumber,
                Address = user.UserPerson.Address,
                DateOfBirth = user.UserPerson.DateOfBirth,
                Role = user.UserPerson.Role
            };

            return View(userDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UserDto userDto)
        {
            if (!ModelState.IsValid)
            {
                var user = context.Users
                    .Include(u => u.UserPerson)
                    .FirstOrDefault(u => u.UserId == userDto.UserId);

                if (user == null)
                {
                    return NotFound();
                }
                user.Username = userDto.Username;
                user.UserPerson.FirstName = userDto.FirstName;
                user.UserPerson.SecondName = userDto.SecondName;
                user.UserPerson.LastName = userDto.LastName;
                user.UserPerson.Email = userDto.Email;
                user.UserPerson.contactNumber = userDto.contactNumber;
                user.UserPerson.Address = userDto.Address;
                user.UserPerson.DateOfBirth = userDto.DateOfBirth;
                user.UserPerson.Role = userDto.Role;

                context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(userDto);


        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }

            try
            {
                var user = context.Users
                    .Include(u => u.UserPerson)
                    .FirstOrDefault(u => u.UserId == id);

                if (user == null)
                {
                    return NotFound();
                }

                if (user.UserPerson != null)
                {
                    context.Persons.Remove(user.UserPerson);  
                } 

                context.Users.Remove(user);  
                context.Users.Remove(user);  
                 
                context.SaveChanges();  

                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return BadRequest($"Error occurred while deleting: {ex.Message}");
            }



        }
        public IActionResult Details(int id)
        {
            if (!SessionHelpercs.IsAdmin(HttpContext))
            {
                return RedirectToAction("Login", "Account");
            }

            var user = context.Users
                .Include(u => u.UserPerson) // 
                .FirstOrDefault(u => u.UserId == id);

            if (user == null)
            {
                return NotFound(); // إذا لم يتم العثور على المستخدم
            }

            var userDto = new UserDto
            {
                UserId = user.UserId,
                Username = user.Username,
                FirstName = user.UserPerson.FirstName,
                SecondName = user.UserPerson.SecondName,
                LastName = user.UserPerson.LastName,
                Email = user.UserPerson.Email,
                contactNumber = user.UserPerson.contactNumber,
                Address = user.UserPerson.Address,
                DateOfBirth = user.UserPerson.DateOfBirth,
                Role = user.UserPerson.Role
            };

            return View(userDto); // عرض صفحة التفاصيل مع البيانات
        }
    }

}
    

Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolProject</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolProject.styles.css" asp-append-version="true" />
    <style>

        header {
            border-radius: 20px;
            overflow: hidden; /* لضمان أن المحتوى داخل الـ header لا يتجاوز الحدود */
           
        }
        /* Sidebar styles */
        #sidebar {
            height: 100vh;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #b0c4de;
            padding-top: 20px;
            transition: all 0.3s;
            z-index: 9999;
            border-radius: 10px;
        }

            #sidebar .nav-item {
                background-color: #b0c4de;
                margin-bottom: 5px;
                border-radius: 7px;
            }

                #sidebar .nav-item a {
                    color: white;
                    border-radius: 7px;
                }

                    #sidebar .nav-item a:hover {
                        background-color: #003f73;
                    }

        #page-content-wrapper {
            margin-left: 250px;
            padding: 20px;
            width: 100%;
        }

        .navbar-collapse {
            margin-left: 250px;
        }

        /* Toggle sidebar */
        #wrapper.toggled #sidebar {
            margin-left: -250px;
        }

        #wrapper.toggled #page-content-wrapper {
            margin-left: 0;
        }
    </style>

</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar">
            <div class="sidebar-heading">
                <h3 class="text-white text-center">School</h3>
            </div>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Index">
                        <i class="fas fa-tachometer-alt"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Index">
                        <i class="fas fa-users"></i> Users
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Staffs" asp-action="Index">
                        <i class="fas fa-user-tie"></i> Staff
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Teacher" asp-action="Index">
                        <i class="fas fa-chalkboard-teacher"></i>  Teachers
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="Index">
                        <i class="fas fa-user-graduate"></i>  Students
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Grades" asp-action="Index">
                        <i class="fas fa-chart-line"></i>  Grades
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Classes" asp-action="Index">
                        <i class="fas fa-door-open"></i>  Classes
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Payments" asp-action="Index">
                        <i class="fas fa-wallet"></i>  Payments
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Course" asp-action="Index">
                        <i class="fas fa-book"></i> Courses
                    </a>
                </li>
                
            </ul>

        </div>

       
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <header >
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolProject</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>

            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- JavaScript to toggle Sidebar -->
    <script>
        document.getElementById("menu-toggle").addEventListener("click", function (e) {
            e.preventDefault();
            document.getElementById("wrapper").classList.toggle("toggled");
        });
    </script>
    @RenderSection("Scripts", required: false)

</body>
</html>

Views/Shared/Login.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f7f9fc;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .login-container {
            background-color: #ffffff;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
        }

            .login-container h2 {
                color: #003f70; /* Navy Blue */
                font-weight: 700;
                text-align: center;
                margin-bottom: 20px;
            }

        .form-group label {
            font-weight: bold;
            color: #003f70;
        }

        .form-control {
            border-radius: 8px;
            border: 2px solid #004e89;
            box-shadow: none;
            transition: border-color 0.3s ease;
        }

            .form-control:focus {
                border-color: #003f70;
                box-shadow: 0 0 10px rgba(0, 78, 137, 0.3);
            }

        .btn-primary {
            background-color: #003f70;
            border-color: #003f70;
            width: 100%;
            padding: 12px;
            font-weight: bold;
            border-radius: 8px;
        }

            .btn-primary:hover {
                background-color: #002b56;
                border-color: #002b56;
            }

        .alert-danger {
            background-color: #f8d7da;
            color: #721c24;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 20px;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 14px;
            color: #003f70;
        }
    </style>
</head>
<body>

    <div class="login-container">
        <h2>@ViewData["Title"]</h2>

        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger">
                @ViewBag.ErrorMessage
            </div>
        }

        <form method="post">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" />
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" />
            </div>

            <button type="submit" class="btn btn-primary">Login</button>
        </form>

        <div class="footer">
            <p>&copy; 2025 Future School. All rights reserved.</p>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolProject.styles.css" asp-append-version="true" />
    </style>
</head>
<body>

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolProject</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>

            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

</body>
</html>